/**
 * RAGService — Retrieval-Augmented Generation for DocuFlow.
 *
 * Implements the full RAG pipeline:
 * 1. Retrieve: embed query → vector search → top-k document chunks
 * 2. Generate: build context prompt → LLM completion → structured response
 *
 * ── WHY RAG? ────────────────────────────────────────────────────────────────
 * LLMs have fixed training cutoffs and don't know about your documents.
 * RAG bridges this gap:
 * - Retrieve relevant document chunks using semantic similarity
 * - Give the LLM just the relevant context (not the whole database)
 * - Ask the LLM to answer using ONLY the provided context
 * - Cite the source chunks in the response
 *
 * ── RETRIEVAL STRATEGY ──────────────────────────────────────────────────────
 * We use pgvector for retrieval (same as SearchService.semanticSearch).
 * The embedding is generated by the AI provider (must match stored embedding model).
 * We retrieve top-k=5 chunks by cosine similarity.
 *
 * ── CONTEXT WINDOW MANAGEMENT ────────────────────────────────────────────────
 * Context budget (approximate):
 * - System prompt: ~300 tokens
 * - User question: ~50 tokens
 * - Conversation history (last 6 turns): ~1200 tokens
 * - Retrieved chunks (5 × ~250 tokens): ~1250 tokens
 * - Answer generation budget: ~2000 tokens
 * Total: ~4800 tokens — well within gpt-4o-mini's 128k context
 *
 * ── CITATIONS ────────────────────────────────────────────────────────────────
 * Citations are returned as { documentId, documentName, chunkIndex } objects.
 * The LLM is instructed to reference sources as "[Doc: Name]" in its response.
 * We parse these references to build structured citation objects.
 */

import { ConflictException, HttpException, Injectable, Logger, NotFoundException } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import type { Message } from '@docuflow/ai';

import { DatabaseService } from '../database/database.service';
import { AiCredentialsService } from './ai-credentials.service';

// ── Types ─────────────────────────────────────────────────────────────────────

export interface RetrievedChunk {
  chunkId: string;
  documentId: string;
  documentName: string;
  content: string;
  chunkIndex: number;
  similarity: number;
}

export interface Citation {
  documentId: string;
  documentName: string;
  chunkIndex: number;
  similarity: number;
}

export interface RAGAnswer {
  /** The LLM's answer text */
  content: string;
  /** Source chunks used to generate the answer */
  citations: Citation[];
  /** True if the answer was generated with context (false = no relevant docs found) */
  hasContext: boolean;
  /** Number of chunks retrieved */
  chunksRetrieved: number;
}

export interface RAGStreamChunk {
  type: 'chunk' | 'citations' | 'done' | 'error';
  content?: string;
  citations?: Citation[];
  error?: string;
}

// ── Constants ─────────────────────────────────────────────────────────────────

/** Number of chunks to retrieve for context */
const TOP_K_CHUNKS = 5;
/** Minimum similarity threshold (cosine distance) */
const MIN_SIMILARITY = 0.3;
/** System prompt for RAG */
const RAG_SYSTEM_PROMPT = `You are DocuFlow AI, an intelligent document assistant.
Your job is to answer questions accurately based ONLY on the provided document context.

RULES:
1. Only use information from the provided context. Do NOT use external knowledge.
2. If the context doesn't contain enough information to answer, say so clearly.
3. Be concise and factual. Avoid speculation.
4. Cite your sources by mentioning the document name when using its content.
5. If multiple documents contain relevant information, synthesize them coherently.

Format your answer in clear, readable prose. Use bullet points for lists.`;

// ── Service ───────────────────────────────────────────────────────────────────

@Injectable()
export class RAGService {
  private readonly logger = new Logger(RAGService.name);

  constructor(
    private readonly credentials: AiCredentialsService,
    private readonly db: DatabaseService,
  ) {}

  /**
   * Check if an AI provider is configured for the organization
   * (its own key from Settings, or the server-wide OPENAI_API_KEY).
   */
  async isAvailable(organizationId: string): Promise<boolean> {
    const ai = await this.credentials.providerFor(organizationId);
    return ai?.isAvailable() ?? false;
  }

  // ──────────────────────────────────────────────────────────────────────────
  // RETRIEVAL: Find relevant document chunks
  // ──────────────────────────────────────────────────────────────────────────

  /**
   * Retrieve the most relevant document chunks for a query.
   * Uses pgvector cosine similarity search.
   */
  async retrieveContext(
    query: string,
    organizationId: string,
    options: {
      topK?: number;
      minSimilarity?: number;
      documentIds?: string[]; // Restrict to specific documents
      folderId?: string;
    } = {},
  ): Promise<RetrievedChunk[]> {
    const {
      topK = TOP_K_CHUNKS,
      minSimilarity = MIN_SIMILARITY,
      documentIds,
    } = options;

    const ai = await this.credentials.providerFor(organizationId);
    if (!ai?.isAvailable()) {
      this.logger.warn('AI provider unavailable — cannot retrieve semantic context');
      return [];
    }

    // Embed the query
    const embedResults = await ai.embed([query]);
    if (!embedResults[0]) {
      this.logger.warn('Embedding generation returned no results');
      return [];
    }

    const queryEmbedding = embedResults[0].embedding;
    const embedding = `[${queryEmbedding.join(',')}]`;

    // Bound parameters only — documentIds come from the request body.
    const docFilter =
      documentIds && documentIds.length > 0
        ? Prisma.sql`AND c."documentId" = ANY(${documentIds}::uuid[])`
        : Prisma.empty;

    const rows = await this.db.$queryRaw<
      Array<{
        chunkId: string;
        documentId: string;
        documentName: string;
        content: string;
        chunkIndex: number;
        similarity: number;
      }>
    >`
      SELECT
        c."id" AS "chunkId",
        c."documentId",
        d."name" AS "documentName",
        c."content",
        c."chunkIndex",
        1 - (c."embedding" <=> ${embedding}::vector) AS similarity
      FROM "document_chunks" c
      JOIN "documents" d ON c."documentId" = d."id"
      WHERE
        c."organizationId" = ${organizationId}::uuid
        AND c."embedding" IS NOT NULL
        AND d."deletedAt" IS NULL
        AND d."status" = 'READY'
        AND 1 - (c."embedding" <=> ${embedding}::vector) >= ${minSimilarity}
        ${docFilter}
      ORDER BY c."embedding" <=> ${embedding}::vector ASC
      LIMIT ${topK}
    `;

    this.logger.debug(
      `Retrieved ${rows.length} chunks for query: "${query.slice(0, 50)}..."`,
    );

    return rows.map((row) => ({
      chunkId: row.chunkId,
      documentId: row.documentId,
      documentName: row.documentName,
      content: row.content,
      chunkIndex: Number(row.chunkIndex),
      similarity: Number(row.similarity),
    }));
  }

  // ──────────────────────────────────────────────────────────────────────────
  // GENERATION: Generate answer with context
  // ──────────────────────────────────────────────────────────────────────────

  /**
   * Generate an answer using retrieved context and conversation history.
   * Non-streaming version — waits for complete response.
   */
  async generateAnswer(
    organizationId: string,
    question: string,
    chunks: RetrievedChunk[],
    conversationHistory: Message[] = [],
  ): Promise<RAGAnswer> {
    const ai = await this.credentials.requireProvider(organizationId);
    const messages = this.buildRAGMessages(question, chunks, conversationHistory);

    const result = await ai.complete(messages, {
      systemPrompt: RAG_SYSTEM_PROMPT,
      maxTokens: 2048,
      temperature: 0.3,
    });

    const citations = chunks.map((chunk) => ({
      documentId: chunk.documentId,
      documentName: chunk.documentName,
      chunkIndex: chunk.chunkIndex,
      similarity: chunk.similarity,
    }));

    this.logger.debug(
      `Generated answer (${result.usage.totalTokens} tokens) for: "${question.slice(0, 50)}..."`,
    );

    return {
      content: result.content,
      citations,
      hasContext: chunks.length > 0,
      chunksRetrieved: chunks.length,
    };
  }

  /**
   * Generate a streaming answer using retrieved context.
   * Yields RAGStreamChunks for SSE transport.
   */
  async *generateAnswerStream(
    organizationId: string,
    question: string,
    chunks: RetrievedChunk[],
    conversationHistory: Message[] = [],
  ): AsyncGenerator<RAGStreamChunk> {
    const messages = this.buildRAGMessages(question, chunks, conversationHistory);

    try {
      const ai = await this.credentials.requireProvider(organizationId);
      for await (const chunk of ai.stream(messages, {
        systemPrompt: RAG_SYSTEM_PROMPT,
        maxTokens: 2048,
        temperature: 0.3,
      })) {
        if (chunk.done) {
          // Send citations at the end
          const citations: Citation[] = chunks.map((c) => ({
            documentId: c.documentId,
            documentName: c.documentName,
            chunkIndex: c.chunkIndex,
            similarity: c.similarity,
          }));

          yield { type: 'citations', citations };
          yield { type: 'done' };
        } else {
          yield { type: 'chunk', content: chunk.content };
        }
      }
    } catch (err) {
      this.logger.error(`Stream generation failed: ${err}`);
      // Provider errors can echo request details (e.g. a masked API key): only
      // pass through our own user-facing messages.
      yield {
        type: 'error',
        error:
          err instanceof HttpException
            ? err.message
            : 'The AI provider failed to answer. Please try again.',
      };
    }
  }

  // ──────────────────────────────────────────────────────────────────────────
  // Document Summarization
  // ──────────────────────────────────────────────────────────────────────────

  /**
   * Generate a summary of a document from its chunks.
   * Uses the full text of the first N chunks (enough for good summary).
   */
  async summarizeDocument(
    documentId: string,
    organizationId: string,
  ): Promise<{ summary: string; keyPoints: string[]; wordCount: number }> {
    const document = await this.db.document.findFirst({
      where: { id: documentId, organizationId, deletedAt: null },
      select: { name: true, mimeType: true, status: true },
    });
    if (!document) {
      throw new NotFoundException('Document not found');
    }
    if (document.status !== 'READY') {
      throw new ConflictException(
        document.status === 'FAILED'
          ? 'This document could not be processed, so it cannot be summarized'
          : 'This document is still being processed — try again shortly',
      );
    }
    const ai = await this.credentials.requireProvider(organizationId);

    // Fetch document chunks (no embedding needed — full text)
    const chunks = await this.db.documentChunk.findMany({
      where: { documentId, organizationId },
      orderBy: { chunkIndex: 'asc' },
      take: 20, // First 20 chunks = ~5000 chars ≈ good summary material
      select: { content: true, chunkIndex: true },
    });

    if (chunks.length === 0) {
      return {
        summary: 'No content available to summarize.',
        keyPoints: [],
        wordCount: 0,
      };
    }

    const fullText = chunks.map((c) => c.content).join('\n\n');
    const wordCount = fullText.split(/\s+/).length;

    const messages: Message[] = [
      {
        role: 'user',
        content: `Please summarize the following document titled "${document.name}":\n\n${fullText}\n\nProvide:
1. A concise summary (2-3 sentences)
2. 3-5 key points as a bullet list

Format your response as JSON:
{
  "summary": "...",
  "keyPoints": ["point 1", "point 2", ...]
}`,
      },
    ];

    const result = await ai.complete(messages, {
      systemPrompt: 'You are a document summarization assistant. Respond with valid JSON only.',
      maxTokens: 1024,
      temperature: 0.2,
    });

    try {
      // Parse the JSON response (strip markdown code blocks if present)
      const jsonStr = result.content
        .replace(/^```json\n?/, '')
        .replace(/\n?```$/, '')
        .trim();
      const parsed = JSON.parse(jsonStr) as { summary: string; keyPoints: string[] };

      return {
        summary: parsed.summary ?? '',
        keyPoints: Array.isArray(parsed.keyPoints) ? parsed.keyPoints : [],
        wordCount,
      };
    } catch {
      // Fallback: treat the whole response as the summary
      return {
        summary: result.content,
        keyPoints: [],
        wordCount,
      };
    }
  }

  // ──────────────────────────────────────────────────────────────────────────
  // Private helpers
  // ──────────────────────────────────────────────────────────────────────────

  /**
   * Build the message array for RAG:
   * [conversation history...] + [context + question]
   */
  private buildRAGMessages(
    question: string,
    chunks: RetrievedChunk[],
    history: Message[],
  ): Message[] {
    const messages: Message[] = [...history];

    // Build context block from retrieved chunks
    let contextBlock = '';
    if (chunks.length > 0) {
      contextBlock = chunks
        .map(
          (chunk, i) =>
            `[${i + 1}] From "${chunk.documentName}" (chunk ${chunk.chunkIndex}):\n${chunk.content}`,
        )
        .join('\n\n---\n\n');
    } else {
      contextBlock = '[No relevant document context was found for this query.]';
    }

    // Final user message: context + question
    const userMessage = `CONTEXT:\n${contextBlock}\n\nQUESTION: ${question}`;
    messages.push({ role: 'user', content: userMessage });

    return messages;
  }
}
