-- ============================================================
-- Migration: Restore search infrastructure
-- ============================================================
--
-- 20260930171236_add_agent_workflows was generated by `prisma migrate dev`
-- while the raw-SQL search columns were not declared in schema.prisma, so it
-- dropped them along with their indexes (and, transitively, the trigger).
-- This restores everything created by 20260930150932_add_search_and_embeddings.
-- The columns are now declared as Unsupported(...) in schema.prisma so future
-- generated migrations leave them alone.
-- ============================================================

CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ── 1. document_chunks.embedding + HNSW index ─────────────────────────────

ALTER TABLE "document_chunks"
  ADD COLUMN IF NOT EXISTS "embedding" vector(1536);

CREATE INDEX IF NOT EXISTS "document_chunks_embedding_hnsw_idx"
  ON "document_chunks"
  USING hnsw ("embedding" vector_cosine_ops)
  WITH (m = 16, ef_construction = 64);

-- ── 2. documents.searchVector + GIN index ─────────────────────────────────

ALTER TABLE "documents"
  ADD COLUMN IF NOT EXISTS "searchVector" tsvector;

UPDATE "documents"
SET "searchVector" =
  setweight(to_tsvector('english', COALESCE("name", '')), 'A') ||
  setweight(to_tsvector('english', COALESCE("description", '')), 'B') ||
  setweight(to_tsvector('english', array_to_string("tags", ' ')), 'C');

CREATE INDEX IF NOT EXISTS "documents_search_vector_gin_idx"
  ON "documents"
  USING gin ("searchVector");

-- ── 3. GIN index on tags, trigram index on name ───────────────────────────

CREATE INDEX IF NOT EXISTS "documents_tags_gin_idx"
  ON "documents"
  USING gin ("tags");

CREATE INDEX IF NOT EXISTS "documents_name_trgm_idx"
  ON "documents"
  USING gin ("name" gin_trgm_ops);

-- ── 4. Trigger: auto-update searchVector ──────────────────────────────────

CREATE OR REPLACE FUNCTION update_document_search_vector()
RETURNS TRIGGER AS $$
BEGIN
  NEW."searchVector" :=
    setweight(to_tsvector('english', COALESCE(NEW."name", '')), 'A') ||
    setweight(to_tsvector('english', COALESCE(NEW."description", '')), 'B') ||
    setweight(to_tsvector('english', array_to_string(COALESCE(NEW."tags", ARRAY[]::text[]), ' ')), 'C');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS "documents_search_vector_trigger" ON "documents";
CREATE TRIGGER "documents_search_vector_trigger"
  BEFORE INSERT OR UPDATE OF "name", "description", "tags"
  ON "documents"
  FOR EACH ROW
  EXECUTE FUNCTION update_document_search_vector();
